name: Fly Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    permissions:
      checks: write  # for coverallsapp/github-action to create new checks
      contents: read  # for actions/checkout to fetch code

    name: Deploy app
    
    services:
      redis:
        image: 'redis:2.8.23'
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379

      - name: Install Node
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node }}

        - name: NPM Install
          uses: bahmutov/npm-install@v1
          with:
            useLockFile: false

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: print secrets
        run: |
            echo "$MY_SECRET" >> config.json
            cat config.json
        shell: bash
        env:
          MY_SECRET: ${{secrets.CONFIG}}
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        