name: Prettier Format Check
on:
  push:
    branches:
      - main
jobs:
  Prettier-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Prettier
        run: npm install --save-dev --save-exact prettier
      - name: Check file format in src folder
        run: npx prettier --write ./src